artifacts_root: artifacts

data_ingenstion:
  root_dir: artifacts/data_ingenstion
  source_url: "https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing"
  local_data_file: artifacts/data_ingenstion/data.zip
  unzip_dir: artifacts/data_ingenstion
